spring:
  application:
    name: divyasphere-platform

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

server:
  port: 8080

  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: INFO

kind: Application
